### ISSUE TITLE
Path Issues

### ISSUE THREAD

**Issue by A75G** [tiredofit/docker-synapse#2]
### Summary

data and other paths are wrong

### Steps to reproduce

after adding the changing DATA_PATH the error was the same but 
`Found file in config directory that does not end in '.yaml': '/data/config/.synapse-version'. IGNORING.`

### Relevant logs and/or screenshots

```
alueError: invalid literal for int() with base 10: '50m'
synapse.app.homeserver(/data//config/) failed to start (exit code: 1). Check the Synapse logfile.
Found file in config directory that does not end in '.yaml': '/data//config/example.com_log.config'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data//config/.synapse-version'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data//config/keys'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data//config/example.com_log.config'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data//config/.synapse-version'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data//config/keys'. IGNORING.
```
```
023-07-19.13:52:54 [STARTING] ** [synapse] [10] Starting Synapse v1.88.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/synapse/app/homeserver.py", line 398, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/synapse/app/homeserver.py", line 388, in main
    hs = setup(sys.argv[1:])
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/app/homeserver.py", line 297, in setup
    config = HomeServerConfig.load_or_generate_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/config/_base.py", line 802, in load_or_generate_config
    obj.parse_config_dict(
  File "/usr/lib/python3.11/site-packages/synapse/config/_base.py", line 823, in parse_config_dict
    self.invoke_all(
  File "/usr/lib/python3.11/site-packages/synapse/config/_base.py", line 422, in invoke_all
    res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/config/repository.py", line 136, in read_config
    self.max_upload_size = self.parse_size(config.get("max_upload_size", "50M"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/config/_base.py", line 198, in parse_size
    return int(value) * size
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '50m'
Found file in config directory that does not end in '.yaml': '/data/config/example.com_log.config'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data/config/keys'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data/config/.synapse-version'. IGNORING.
synapse.app.homeserver(/data/config/) failed to start (exit code: 1). Check the Synapse logfile.
Found file in config directory that does not end in '.yaml': '/data/config/example.com_log.config'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data/config/keys'. IGNORING.
Found file in config directory that does not end in '.yaml': '/data/config/.synapse-version'. IGNORING.
2023-07-19.13:52:58 [STARTING] ** [synapse] [11] Starting Synapse v1.88.0
```
```
/ # cd /data/config/
/data/config # ls -la
total 38
drwxr-xr-x    1 synapse  synapse          6 Jul 19 13:52 .
drwxr-xr-x    8 synapse  synapse          9 Jul 19 13:52 ..
-rw-r--r--    1 root     root            95 Jul 19 13:52 .synapse-version
-rw-r--r--    1 synapse  synapse       1250 Jul 19 13:52 example.com_log.config
-rw-r--r--    1 synapse  synapse       9574 Jul 19 13:52 homeserver.yaml
-rw-r--r--    1 root     root           568 Jul 19 13:52 key
```

### Environment

- Image version / tag: tiredofit/synapse:0.8.10

<details>

docker run
  -d
  --name='synapse'
  --net='bridge'
  --privileged=true
  -e 'TIMEZONE'='America/Vancouver'
  -e 'SERVER_NAME'='example.com'
  -e 'SERVER_URL'='https://example.com'
  -e 'CREATE_ADMIN_USER'='TRUE'
  -e 'ADMIN_PASS'='tiredofit'
  -e 'ADMIN_USER'='synapse'
  -e 'CONTACT_ADMIN_EMAIL'='admin@example.com'
  -e 'ENABLE_HTTP'='TRUE'
  -e 'ENABLE_METRICS'='TRUE'
  -e 'HTTP_ENABLE_COMPRESSION'='TRUE'
  -e 'HTTP_ENABLE_TLS'='FALSE'
  -e 'HTTP_ENABLE_X_FORWARDED'='TRUE'
  -e 'HTTP_LISTEN_IP'='0.0.0.0'
  -e 'HTTP_LISTEN_PORT'='8008'
  -e 'HTTP_MODE'='client,federation'
  -e 'ENABLE_MEDIA_REPO'='TRUE'
  -e 'MEDIA_DYNAMIC_THUMBNAILS'='TRUE'
  -e 'MEDIA_MAX_UPLOAD_SIZE'='50m'
  -e 'MEDIA_MAX_IMAGE_PIXELS'='32m'
  -e 'MEDIA_MAX_SPIDER_SIZE'='10m'
  -e 'MEDIA_RETENTION_LOCAL'='90d'
  -e 'MEDIA_RETENTION_REMOTE'='14d'
  -e 'DB_TYPE'='postgres'
  -e 'DB_HOST'='10.0.10.20'
  -e 'DB_USER'='matrix'
  -e 'DB_PASS'='password'
  -e 'DB_PORT'='5432'
  -e 'DB_NAME'='matrix'
  -e 'DATA_PATH'='/data'
  -e 'CONFIG_FILE'='homeserver.yaml'
  -e 'CONFIG_PATH'='/data/confg'
  -p '8008:8008/tcp'
  -v '/mnt/user/appdata/synapse/certs/':'/data/certs':'rw'
  -v '/mnt/user/appdata/synapse/config/':'/data/config':'rw'
  -v '/mnt/user/appdata/synapse/media/':'/data/media':'rw'
  -v '/mnt/user/appdata/synapse/templates/':'/data/templates':'rw'
  -v '/mnt/user/appdata/synapse/uploads/':'/data/uploads':'rw'
  -v '/mnt/user/appdata/synapse/logs/':'/logs':'rw' 'tiredofit/synapse' 

</details>

    
### Possible fixes
https://github.com/tiredofit/docker-synapse/blob/main/install/assets/defaults/10-synapse
Im not sure but i think adding data path var with /data fixed one issue but still

**Comment by tiredofit** [comment]
Interesting. I have yet to upgrade to this version on my own instance yet.
I too see those IGNORE warnings because it doesn't like that I have other files that are not yaml in there to parse, but I'm not too concerned.

I see that the problem is related to something in your homeserver.yaml with the value of `50m`  - What is it?

**Comment by tiredofit** [comment]
Great perfect! I just cleaned up the README.
